apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: osp-master-0
spec:
  desiredState:
    interfaces:
    - description: internalapi vlan interface
      ipv4:
        address:
        - ip: 10.103.1.10
          prefix-length: 24
        enabled: true
        dhcp: false
      ipv6:
        enabled: false
      name: internalapi
      state: up
      type: vlan
      vlan:
        base-iface: enp8s0
        id: 103
        reorder-headers: true

    - description: tenant vlan interface
      ipv4:
        address:
        - ip: 10.105.1.10
          prefix-length: 24
        enabled: true
        dhcp: false
      ipv6:
        enabled: false
      name: tenant
      state: up
      type: vlan
      vlan:
        base-iface: enp8s0
        id: 105
        reorder-headers: true

    - description: storage vlan interface
      ipv4:
        address:
        - ip: 10.106.1.10
          prefix-length: 24
        enabled: true
        dhcp: false
      ipv6:
        enabled: false
      name: storage
      state: up
      type: vlan
      vlan:
        base-iface: enp7s0
        id: 106
        reorder-headers: true         

    - description: designate vlan interface
      ipv4:
        address:
        - ip: 10.101.1.10
          prefix-length: 24
        enabled: true
        dhcp: false
      ipv6:
        enabled: false
      name: designate
      state: up
      type: vlan
      vlan:
        base-iface: enp8s0
        id: 101
        reorder-headers: true

    - description: designate external vlan interface
      ipv4:
        address:
        - ip: 10.104.1.10
          prefix-length: 24
        enabled: true
        dhcp: false
      ipv6:
        enabled: false
      name: designateext
      state: up
      type: vlan
      vlan:
        base-iface: enp8s0
        id: 104
        reorder-headers: true 

    - description: octavia vlan interface
      ipv4:
        enabled: false
        dhcp: false
      ipv6:
        enabled: false
      name: octavia
      state: up
      type: vlan
      vlan:
        base-iface: enp8s0
        id: 102
        reorder-headers: true
    - bridge:
        options:
          stp:
            enabled: false
        port:
        - name: octavia
      ipv4:
        address:
        - ip: 10.102.1.10
          prefix-length: 24
        enabled: true
        dhcp: false
      description: Configuring bridge octbr
      mtu: 1500
      name: octbr
      state: up
      type: linux-bridge          
  nodeSelector:
    kubernetes.io/hostname: master0.rhoso.keenable.in
