apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: osp-master-0
spec:
  desiredState:
    interfaces:
    - description: internalapi vlan interface
      ipv4:
        address:
        - ip: 10.103.1.10
          prefix-length: 24
        enabled: true
        dhcp: false
      ipv6:
        enabled: false
      name: internalapi
      state: up
      type: vlan
      vlan:
        base-iface: enp8s0
        id: 103
        reorder-headers: true

    - description: tenant vlan interface
      ipv4:
        address:
        - ip: 10.105.1.10
          prefix-length: 24
        enabled: true
        dhcp: false
      ipv6:
        enabled: false
      name: tenant
      state: up
      type: vlan
      vlan:
        base-iface: enp8s0
        id: 105
        reorder-headers: true

    - description: storage vlan interface
      ipv4:
        address:
        - ip: 10.106.1.10
          prefix-length: 24
        enabled: true
        dhcp: false
      ipv6:
        enabled: false
      name: storage
      state: up
      type: vlan
      vlan:
        base-iface: enp7s0
        id: 106
        reorder-headers: true          
  nodeSelector:
    kubernetes.io/hostname: master0.rhoso.keenable.in
