apiVersion: core.openstack.org/v1beta1
kind: OpenStackControlPlane
metadata:
  name: openstack-control-plane
  namespace: openstack
spec:
  secret: osp-secret
  storageClass: ocs-external-storagecluster-ceph-rbd
  cinder:
    apiOverride:
      route: {}
    template:
      databaseInstance: openstack
      secret: osp-secret
      cinderAPI:
        replicas: 3
        override:
          service:
            internal:
              metadata:
                annotations:
                  metallb.universe.tf/address-pool: internalapi
                  metallb.universe.tf/allow-shared-ip: internalapi
                  metallb.universe.tf/loadBalancerIPs: 10.103.1.80
              spec:
                type: LoadBalancer
      cinderScheduler:
        replicas: 1
      cinderBackup:
        networkAttachments:
        - storage
        replicas: 0 # backend needs to be configured to activate the service
      cinderVolumes:
        ceph:
          customServiceConfig: |
            [DEFAULT]
            enabled_backends=ceph          
            [ceph]
            volume_backend_name=ceph
            volume_driver=cinder.volume.drivers.rbd.RBDDriver
            rbd_ceph_conf=/etc/ceph/ceph.conf
            rbd_user=admin
            rbd_pool=volumes
            rbd_flatten_volume_from_snapshot=False
            rbd_secret_uuid=77f8c2de-e245-11f0-9bf2-5254000947d1
            #volume:
          networkAttachments:
          - storage
          replicas: 1 # backend needs to be configured to activate the service
  nova:
    apiOverride:
      route: {}
    template:
      apiServiceTemplate:
        replicas: 3
        override:
          service:
            internal:
              metadata:
                annotations:
                  metallb.universe.tf/address-pool: internalapi
                  metallb.universe.tf/allow-shared-ip: internalapi
                  metallb.universe.tf/loadBalancerIPs: 10.103.1.80
              spec:
                type: LoadBalancer
      metadataServiceTemplate:
        replicas: 3
        override:
          service:
            metadata:
              annotations:
                metallb.universe.tf/address-pool: internalapi
                metallb.universe.tf/allow-shared-ip: internalapi
                metallb.universe.tf/loadBalancerIPs: 10.103.1.80
            spec:
              type: LoadBalancer
      schedulerServiceTemplate:
        replicas: 3
        customServiceConfig: |
          [filter_scheduler]
          enabled_filters = AvailabilityZoneFilter, ComputeFilter, ComputeCapabilitiesFilter,ImagePropertiesFilter, ServerGroupAntiAffinityFilter, ServerGroupAffinityFilter, PciPassthroughFilter,AggregateInstanceExtraSpecsFilter
          available_filters = nova.scheduler.filters.all_filters
      cellTemplates:
        cell0:
          cellDatabaseAccount: nova-cell0
          cellDatabaseInstance: openstack
          cellMessageBusInstance: rabbitmq
          hasAPIAccess: true
        cell1:
          cellDatabaseAccount: nova-cell1
          cellDatabaseInstance: openstack-cell1
          cellMessageBusInstance: rabbitmq-cell1
          noVNCProxyServiceTemplate:
            enabled: true
            networkAttachments:
            - ctlplane
          hasAPIAccess: true
      secret: osp-secret

  dns:
    enabled: true
    template:
      options:
      - key: server
        values:
        - 10.100.1.1
      override:
        service:
          metadata:
            annotations:
              metallb.universe.tf/address-pool: ctlplane
              metallb.universe.tf/allow-shared-ip: ctlplane
              metallb.universe.tf/loadBalancerIPs: 10.100.1.82
          spec:
            type: LoadBalancer
      replicas: 2
  galera:
    enabled: true
    templates:
      openstack:
        storageRequest: 5000M
        secret: osp-secret
        replicas: 3
      openstack-cell1:
        storageRequest: 5000M
        secret: osp-secret
        replicas: 3
  keystone:
    apiOverride:
      route: {}
    template:
      override:
        service:
          internal:
            metadata:
              annotations:
                metallb.universe.tf/address-pool: internalapi
                metallb.universe.tf/allow-shared-ip: internalapi
                metallb.universe.tf/loadBalancerIPs: 10.103.1.80
            spec:
              type: LoadBalancer
      databaseInstance: openstack
      secret: osp-secret
      replicas: 3
  barbican:
    apiOverride:
      route: {}
    template:
      databaseInstance: openstack
      secret: osp-secret
      barbicanAPI:
        replicas: 3
        override:
          service:
            internal:
              metadata:
                annotations:
                  metallb.universe.tf/address-pool: internalapi
                  metallb.universe.tf/allow-shared-ip: internalapi
                  metallb.universe.tf/loadBalancerIPs: 10.103.1.80
              spec:
                type: LoadBalancer
      barbicanWorker:
        replicas: 3
      barbicanKeystoneListener:
        replicas: 1
  memcached:
    templates:
      memcached:
         replicas: 3
  neutron:
    apiOverride:
      route: {}
    template:
      customServiceConfig: |
         [DEFAULT]
         dns_domain = keenable.org.
         external_dns_driver = designate
         [ml2]
         extension_drivers=qos,port_security,subnet_dns_publish_fixed_ip
         [designate]
         url = https://designate-internal.openstack.svc:9001/v2
         auth_type = password
         auth_url = {{ .KeystoneInternalURL }}
         username = {{ .ServiceUser }}
         password = {{ .ServicePassword }}
         project_name = service
         project_domain_name = Default
         user_domain_name = Default
         allow_reverse_dns_lookup = true
         ipv4_ptr_zone_prefix_size = 24
         ipv6_ptr_zone_prefix_size = 116
         ptr_zone_email = admin@keenable.org
      replicas: 3
      override:
        service:
          internal:
            metadata:
              annotations:
                metallb.universe.tf/address-pool: internalapi
                metallb.universe.tf/allow-shared-ip: internalapi
                metallb.universe.tf/loadBalancerIPs: 10.103.1.80
            spec:
              type: LoadBalancer
      databaseInstance: openstack
      secret: osp-secret
      networkAttachments:
      - internalapi
  swift:
    enabled: false
    proxyOverride:
      route: {}
    template:
      swiftProxy:
        networkAttachments:
        - storage
        override:
          service:
            internal:
              metadata:
                annotations:
                  metallb.universe.tf/address-pool: internalapi
                  metallb.universe.tf/allow-shared-ip: internalapi
                  metallb.universe.tf/loadBalancerIPs: 10.103.1.80
              spec:
                type: LoadBalancer
        replicas: 2
      swiftRing:
        ringReplicas: 3
      swiftStorage:
        networkAttachments:
        - storage
        replicas: 3
        storageRequest: 100Gi
  ovn:
    template:
      ovnDBCluster:
        ovndbcluster-nb:
          replicas: 3
          dbType: NB
          storageRequest: 10G
          networkAttachment: internalapi
        ovndbcluster-sb:
          replicas: 3
          dbType: SB
          storageRequest: 10G
          networkAttachment: internalapi
      ovnNorthd: {}
      ovnController:
        networkAttachment: tenant
        nicMappings:
          datacentre: br-ex
          octavia: octbr
  placement:
    apiOverride:
      route: {}
    template:
      override:
        service:
          internal:
            metadata:
              annotations:
                metallb.universe.tf/address-pool: internalapi
                metallb.universe.tf/allow-shared-ip: internalapi
                metallb.universe.tf/loadBalancerIPs: 10.103.1.80
            spec:
              type: LoadBalancer
      databaseInstance: openstack
      replicas: 3
      secret: osp-secret
  rabbitmq:
    templates:
      rabbitmq:
        replicas: 3
        override:
          service:
            metadata:
              annotations:
                metallb.universe.tf/address-pool: internalapi
                metallb.universe.tf/loadBalancerIPs: 10.103.1.85
            spec:
              type: LoadBalancer
      rabbitmq-cell1:
        replicas: 3
        override:
          service:
            metadata:
              annotations:
                metallb.universe.tf/address-pool: internalapi
                metallb.universe.tf/loadBalancerIPs: 10.103.1.86
            spec:
              type: LoadBalancer
  telemetry:
    enabled: true
    template:
      metricStorage:
        enabled: false
        dashboardsEnabled: true
        dataplaneNetwork: ctlplane
        networkAttachments:
          - ctlplane
        monitoringStack:
          alertingEnabled: false
          scrapeInterval: 30s
          storage:
            strategy: persistent
            retention: 24h
            persistent:
              pvcStorageRequest: 20G
      autoscaling:
        enabled: false
        aodh:
          databaseAccount: aodh
          databaseInstance: openstack
          passwordSelector:
            aodhService: AodhPassword
          rabbitMqClusterName: rabbitmq
          serviceUser: aodh
          secret: osp-secret
        heatInstance: heat
      ceilometer:
        enabled: true
        secret: osp-secret
        serviceUser: ceilometer
      logging:
        enabled: false

###--
  horizon:
   apiOverride:
   enabled: true
   template:
    customServiceConfig: ""
    extraMounts: []
    memcachedInstance: memcached
    override: {}
    preserveJobs: false
    replicas: 3
    resources: {}
    secret: osp-secret
###Ironic
  ironic:
   enabled: true
   template:
    databaseInstance: openstack
    ironicAPI:
      replicas: 1
    ironicConductors:
    - replicas: 1
      storageRequest: 50G
    ironicInspector:
      replicas: 1
    ironicNeutronAgent:
      replicas: 1
    secret: osp-secret
###Heat
  heat:
   apiOverride:
     route: {}
   cnfAPIOverride:
     route: {}
   enabled: true
   template:
     databaseAccount: heat
     databaseInstance: openstack
     heatAPI:
      override:
        service:
         internal:
           metadata:
             annotations:
               metallb.universe.tf/address-pool: internalapi
               metallb.universe.tf/allow-shared-ip: internalapi
               metallb.universe.tf/loadBalancerIPs: 10.103.1.82
           spec:
            type: LoadBalancer
      replicas: 3
     heatCfnAPI:
       override: {}
       replicas: 1
       resources: {}
     heatEngine:
       replicas: 3
       resources: {}
     memcachedInstance: memcached
     passwordSelectors:
       authEncryptionKey: HeatAuthEncryptionKey
       service: HeatPassword
     preserveJobs: false
     rabbitMqClusterName: rabbitmq
     secret: osp-secret
     serviceUser: heat


############ Glance ######################
  glance:
    enabled: true
    apiOverrides:
      default:
        route: {}
    template:
      customServiceConfig: |
        [DEFAULT]
        enabled_backends = image-conversion:rbd
        [glance_store]
        default_backend = image-conversion
        [image-conversion]
        rbd_store_ceph_conf = /etc/ceph/ceph.conf
        store_description = "RBD backend"
        rbd_store_pool = images
        rbd_store_user = admin
      databaseInstance: openstack
      storage:
        storageRequest: 5G
      secret: osp-secret
      keystoneEndpoint: default
      glanceAPIs:
        default:
          replicas: 1 
          override:
            service:
              internal:
                metadata:
                  annotations:
                    metallb.universe.tf/address-pool: internalapi
                    metallb.universe.tf/allow-shared-ip: internalapi
                    metallb.universe.tf/loadBalancerIPs: 10.103.1.80
                spec:
                  type: LoadBalancer
          networkAttachments:
          - storage
#######   octavia ###############
  octavia:
     enabled: true
     template:
       databaseInstance: openstack
       redisServiceName: octavia-redis
       octaviaHousekeeping:
         networkAttachments:
           - octavia
       octaviaHealthManager:
         networkAttachments:
           - octavia
       octaviaWorker:
         networkAttachments:
           - octavia
       amphoraImageContainerImage: registry.redhat.io/rhoso/octavia-amphora-image-rhel9@sha256:312cd5e8ea9fe261c1929aefececbeb22afe5e433ae76ef0860d98e561db21c9
  redis:
     enabled: true
     templates:
       octavia-redis:
         replicas: 1
       designate-redis:
         replicas: 1           
  extraMounts:
    - name: v1
      region: r1
      extraVol:
        - propagation:
          - CinderVolume
          - CinderBackup
          - GlanceAPI
          - ManilaShare
          extraVolType: Ceph
          volumes:
          - name: ceph
            secret:
              secretName: ceph-conf-files
          mounts:
          - name: ceph
            mountPath: "/etc/ceph"
            readOnly: true

###### DNS as a service ################

  designate:
    apiOverride:
      route: {}
    enabled: true
    template:
      nsRecords:
        - hostname: ns1.keenable.org.
          priority: 1
        - hostname: ns2.keenable.org.
          priority: 2
      designateAPI:
        networkAttachments:
        - internalapi
        override:
          service:
            internal:
              metadata:
                annotations:
                  metallb.universe.tf/address-pool: internalapi
                  metallb.universe.tf/allow-shared-ip: internalapi
                  metallb.universe.tf/loadBalancerIPs: 10.103.1.80
              spec:
                type: LoadBalancer
      designateBackendbind9:
        controlNetworkName: designate
        networkAttachments:
          - designate
        override:
          services:
            - metadata:
                annotations:
                  metallb.universe.tf/address-pool: designateext
                  metallb.universe.tf/allow-shared-ip: designateext
                  metallb.universe.tf/loadBalancerIPs: 10.104.1.80
              spec:
                type: LoadBalancer
            - metadata:
                annotations:
                  metallb.universe.tf/address-pool: designateext
                  metallb.universe.tf/allow-shared-ip: designateext
                  metallb.universe.tf/loadBalancerIPs: 10.104.1.81
              spec:
                type: LoadBalancer
            - metadata:
                annotations:
                  metallb.universe.tf/address-pool: designateext
                  metallb.universe.tf/allow-shared-ip: designateext
                  metallb.universe.tf/loadBalancerIPs: 10.104.1.82
              spec:
                type: LoadBalancer
        replicas: 3
        resources: {}
        serviceUser: designate
        storageClass: ocs-external-storagecluster-ceph-rbd
        storageRequest: 10G
      designateCentral:
        replicas: 3
      designateMdns:
        networkAttachments:
          - designate
        replicas: 3
      designateProducer:
        replicas: 3
      designateUnbound:
        defaultConfigOverwrite:
          01-unbound.conf: |
            server:
              verbosity: 2
              access-control: 172.28.0.0/24 allow
              access-control: 100.64.0.0/10 allow
              module-config: "iterator"
          forwarders.conf: |
            forward-zone:
              name: "."
              forward-addr: 172.11.5.155
              forward-addr: 172.12.5.155
        networkAttachments:
          - designate
        override:
          services:
            - metadata:
                annotations:
                  metallb.universe.tf/address-pool: designateext
                  metallb.universe.tf/allow-shared-ip: designateext
                  metallb.universe.tf/loadBalancerIPs: 10.104.1.90
              spec:
                type: LoadBalancer
            - metadata:
                annotations:
                  metallb.universe.tf/address-pool: designateext
                  metallb.universe.tf/allow-shared-ip: designateext
                  metallb.universe.tf/loadBalancerIPs: 10.104.1.91
              spec:
                type: LoadBalancer
            - metadata:
                annotations:
                  metallb.universe.tf/address-pool: designateext
                  metallb.universe.tf/allow-shared-ip: designateext
                  metallb.universe.tf/loadBalancerIPs: 10.104.1.93
              spec:
                type: LoadBalancer
        replicas: 3
        resources: {}
        stubZones:
          - name: keenable.org
          - name: anotherkeenable.org
      designateWorker:
        databaseAccount: designate
        networkAttachments:
          - designate
        replicas: 3
