apiVersion: instanceha.openstack.org/v1beta1
kind: InstanceHa
metadata:
  name: instanceha-0
spec:
  caBundleSecretName: combined-ca-bundle
  fencingSecret: fencing-0

  #instanceHaConfigMap:

  #networkAttachments: ['internalapi']
  #instanceHaKdumpPort:

  #openStackCloud: "default"
  #openStackConfigMap:
  #openStackConfigSecret:

  #nodeSelector:
