apiVersion: network.openstack.org/v1beta1
kind: NetConfig
metadata:
  name: openstacknetconfig
  namespace: openstack
spec:
  networks:
  - name: CtlPlane
    dnsDomain: ctlplane.rhoso.keenable.in
    subnets:
    - name: subnet1
      allocationRanges:
      - end: 10.100.1.120
        start: 10.100.1.100
      - end: 10.100.1.200
        start: 10.100.1.150
      cidr: 10.100.1.0/24
      gateway: 10.100.1.1
  - name: InternalApi
    dnsDomain: internalapi.rhoso.keenable.in
    subnets:
    - name: subnet1
      allocationRanges:
      - end: 10.103.1.250
        start: 10.103.1.100
      excludeAddresses:
      - 10.103.1.10
      - 10.103.1.11
      - 10.103.1.12
      cidr: 10.103.1.0/24
      vlan: 103
  - name: Storage
    dnsDomain: storage.rhoso.keenable.in
    subnets:
    - name: subnet1
      allocationRanges:
      - end: 10.106.1.250
        start: 10.106.1.100
      cidr: 10.106.1.0/24
      vlan: 106
  - name: Tenant
    dnsDomain: tenant.rhoso.keenable.in
    subnets:
    - name: subnet1
      allocationRanges:
      - end: 10.105.1.250
        start: 10.105.1.100
      cidr: 10.105.1.0/24
      vlan: 105
